[WIP] Rentention policy
salt-formulas/salt-formula-influxdb pull request #16
Opened 2016-12-02 16:23 UTC by SwannCroiset

2016-12-05 08:13 UTC, elemoine commented on influxdb/server.sls
> +influxdb_retention_policy_{{db.name}}{{ rp_name }}:
Do you want to add an underscore between the db name and the rp name in the declaration ID?

2016-12-05 09:01 UTC, simonpasquier requested changes

2016-12-05 09:01 UTC, simonpasquier commented on influxdb/server.sls
> +    {% set query_rentention_policy = 'RETENTION POLICY {} ON {} DURATION {} REPLICATION {}'.format(
s/query_rentention_policy/query_retention_policy/

2016-12-05 09:01 UTC, simonpasquier commented on influxdb/server.sls
> +    - name: curl -s -S -POST "{{ url_for_query }}" --data-urlencode "q=CREATE {{ query_rentention_policy }}{%- if shard_duration %} SHARD DURATION {{ shard_duration }}{%- endif %}"|grep "policy alrea
not sure why "SHARD DURATION ..." isn't added to `query_rentention_policy` before.

2016-12-05 09:02 UTC, simonpasquier commented on influxdb/server.sls
> +        rp_name, db.name, duration, replication)
don't you want to manage DEFAULT too?

2016-12-05 09:26 UTC, SwannCroiset commented on influxdb/server.sls
> +        rp_name, db.name, duration, replication)
The default PR is named **autogen** with InfluxDB 1.x

2016-12-05 09:30 UTC, SwannCroiset commented on influxdb/server.sls
> +influxdb_retention_policy_{{db.name}}{{ rp_name }}:
not especially but if you prefer I'll add one

2016-12-05 09:30 UTC, SwannCroiset commented on influxdb/server.sls
> +    {% set query_rentention_policy = 'RETENTION POLICY {} ON {} DURATION {} REPLICATION {}'.format(
done

2016-12-05 09:32 UTC, SwannCroiset commented on influxdb/server.sls
> +    - name: curl -s -S -POST "{{ url_for_query }}" --data-urlencode "q=CREATE {{ query_rentention_policy }}{%- if shard_duration %} SHARD DURATION {{ shard_duration }}{%- endif %}"|grep "policy alrea
b/c we cannot add jinja logic inside a jinja **set** directive

2016-12-05 09:55 UTC, SwannCroiset commented on influxdb/server.sls
> +        rp_name, db.name, duration, replication)
ok, understood your point

2016-12-05 11:54 UTC, gthvn1 approved these changes

2016-12-05 15:45 UTC, SwannCroiset commented
@simonpasquier please review again, I addressed all your points

2016-12-06 10:24 UTC, simonpasquier approved these changes

2016-12-06 10:42 UTC, elemoine approved these changes

2016-12-06 10:51 UTC, merged